apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: redis
    targetRevision: 22.0.7
    
    helm:
      values: |
        auth:
          enabled: false
        
        master:
          persistence:
            enabled: false
          containerSecurityContext:
            runAsUser: 1001
            fsGroup: 1001
          service:
            type: ClusterIP

        replica:
          replicaCount: 0

        commonLabels:
          app: redis

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true