---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secrets
  namespace: default
spec:
  encryptedData:
    VITE_BACKEND_URL: AgA04aVjSdEIaj6KHQZ+lNe+lIEJN6plkaGfTFMZE3hZjHbineUv2jgmMJNaj25qbnBjpRRu3veInR2A6J8Zj5kLzaMSr2g7ptbKVeNDyRjY8RDfBqhE9nTferctDRiBu55yKYoLDqXp1TNfRS0YLYGRA4OMxQKAjy6PsZ3PcbLtrGl5GcB9RGjV02+gv8IwSwILZuQ6sU779W86dNCTE3c4S0zx/GBEWLAOAFBMvH/flO4tXSBamSu/4/JaM9x+gEKyewg1jwiLi4rSj5Kww54n8GJlhCbNnYLBX1m3onPXqEom/gua8uQ2MaMHOkdAin454wM88r9HD9v5DbrLhSLV+Ic+On9Q2YZt8MVsl8JvsZVQuGfCJ8REDekOF+GnRm66JUMCOnABnJy7xvPgigaX4GrkVLI4KlnkY95PcM9AKGsNEgPJfqSTl4ThhyDO1M0mHptCNydbRSsFj899+BFHbPEU8XjthC3HN+qE6w8cVa94DbpOhxmLbo/wFtLTuxWjU5o8Ukpsra7P9++CKdTWMjWTmJWcHH+WxyVOMnszo4rBvewTB9i4FUJuhL4l2o6aH3e/lATDE5kLjYh15DGtuhylitJzkMsmWKgrzPk0UwydoViZnfoYxc6fN5xqleDfLQxdUAtzE+loJ5jJmJNxtGwNDbPtt0NZNVjBP3dQjtJqS39kYQh+dzbTtbRvWRtFjUREfujHodOnkW/uUkPcsCv5Fp5V
  template:
    metadata:
      name: frontend-secrets
      namespace: default
