# Fichier: apps/cluster-tools.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-tools
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com:sisypheus/capsule-infra.git'
    targetRevision: HEAD
    path: cluster-tools
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true