apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 22.0.7
    chart: redis
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  values: |
    master:
      persistence:
        enabled: false # Pas besoin de persistance pour un PaaS éphémère
      containerSecurityContext:
        runAsUser: 1001 # Utiliser un UID non-root pour la sécurité
        fsGroup: 1001
      service:
        type: ClusterIP # Seulement accessible en interne
    replica:
      replicaCount: 0 # Pas besoin de répliques pour un setup simple
    auth:
      enabled: false # Désactiver l'authentification pour la simplicité (pour l'instant)