apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-applicationset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/sisypheus/capsule-infra.git
      revision: HEAD
      files:
      - path: "apps/system/*.yaml"

  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{source_repo | default "https://github.com/sisypheus/capsule-infra.git"}}'
        targetRevision: '{{source_version | default "HEAD"}}'
        path: '{{source_path}}'
        chart: '{{source_chart}}'
        helm:
          values: '{{helm_values}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true