apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - name: backend
          namespace: default
        - name: frontend
          namespace: default
        - name: redis
          namespace: default
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/sisypheus/capsule-infra'
        targetRevision: HEAD
        path: 'charts/{{name}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true